name: Build and Run GoogleTest

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore GameEngine.sln

      - name: Build solution
        run: |
          msbuild GameEngine.sln `
            /p:Configuration=Release `
            /p:Platform="x64" `
            /m

      - name: Run GoogleTest
        run: |
          .\GameEngine\x64\Release\TestPhysicsEngine.exe --gtest_color=yes
